// packages/vue/src/RenderFrame.vue
<script setup>
import { inject, onMounted, ref } from "vue";

const { page } = defineProps({
    page: {},
});

const pages = inject("inertia-frames-vue::pages");
const frame = inject("inertia-frames-vue::frame");

let component = ref();
let status = ref("processing");

onMounted(() => {
    pages[`${page.path}.vue`]().then((module) => {
        component.value = module.default;

        status.value = "rendered";
    });
});
</script>

<template>
    <div>
        <div v-if="status === 'processing'">Processing</div>

        <div v-if="status === 'failed'">Could not render page</div>

        <Component
            v-if="status === 'rendered'"
            :is="component"
            v-bind="{
                ...page.properties,
                frame,
            }"
        />
    </div>
</template>

<style scoped></style>

// packages/svelte/src/RenderFrame.svelte
<script>
	import { getContext } from "svelte"
	import { TheFrameDrawerContextKey } from "./TheFrameDrawer.svelte"

	export let frame

	const { pages } = getContext(TheFrameDrawerContextKey)

	const resolvePage = () => pages[`${frame.path}.svelte`]().then((module) => module.default)
</script>

{#await resolvePage()}
	<div>Loading</div>
{:then page}
	<svelte:component this={page} {...frame.properties} />
{:catch _}
	<div>Error</div>
{/await}
